### PR TITLE
update one file about torch/tf label switcher

### PR DESCRIPTION
**Pull request by coronaPolvo**

### CODE REVIEW

**Review by visualDust — CHANGES_REQUESTED** [review]
please resubmit the commit msg as detailed as possible.

for example: 
```
updated the PyTorch part in docs/ch1p1/[1]operate-on-data
```
or stuff like that would be helpful.

**Comment by lideming** [comment]
@visualDust 
> please resubmit the commit msg as detailed as possible.

For example:

```
any
```

**Comment by visualDust** [comment]
> @visualDust
> 
> > please resubmit the commit msg as detailed as possible.
> 
> For example:
> 
> ```
> any
> ```

好汉不提当年勇

**Review by visualDust — APPROVED** [review]
thats better

**Pull request merged**
