### PR TITLE
Submitting notes about KinD and GhostNet

### PR DESCRIPTION
**Pull request by RuoMengAwA**

### CODE REVIEW

**Comment by visualDust** [comment]
@lideming check the build error (idk what it means)

**Comment by lideming** [comment]
Filenames are invalid:
```
[49]GhostNet—More-Features-from-Cheap-Operations.md
            ^ This is not a normal "-"

[50]Kindling the Darkness-A-Practical-Low-light-Image-Enhancer.md
            ^   ^ Spaces are not allowed
```

**Review by visualDust — CHANGES_REQUESTED** [review]
[49]GhostNet—More-Features-from-Cheap-Operations.md
            ^ This is not a normal "-"

[50]Kindling the Darkness-A-Practical-Low-light-Image-Enhancer.md
            ^   ^ Spaces are not allowed

**Review by visualDust — CHANGES_REQUESTED** [review]
[49]GhostNet—More-Features-from-Cheap-Operations.md
                      ^ not a standard hyphen

**Comment by visualDust** [comment]
SGTM

**Pull request merged**
